apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: test
type: Opaque
data:
  # username: admin  -> Base64 编码为: YWRtaW4=
  # password: s3cr3t -> Base64 编码为: czNjcjN0
  username: YWRtaW4=
  password: czNjcjN0
